//INSTITUTE
export enum AuthActionType {
    CHECK_AUTHORIZATION= 'CHECK_AUTHORIZATION',
    LOGIN_REQUEST= 'LOGIN_REQUEST',
    LOGOUT= 'LOGOUT',
    LOGIN_SUCCESS= 'LOGIN_SUCCESS',
    LOGIN_ERROR= 'LOGIN_ERROR',
}